// Code generated by go generate; DO NOT EDIT.
package observer

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tWaitOBServerReady            ttypes.TaskName = "wait observer ready"
	tAddServer                    ttypes.TaskName = "add server"
	tWaitOBClusterBootstrapped    ttypes.TaskName = "wait obcluster bootstrapped"
	tCreateOBServerPod            ttypes.TaskName = "create observer pod"
	tCreateOBServerPVC            ttypes.TaskName = "create observer pvc"
	tDeleteOBServerInCluster      ttypes.TaskName = "delete observer in cluster"
	tAnnotateOBServerPod          ttypes.TaskName = "annotate observer pod"
	tUpgradeOBServerImage         ttypes.TaskName = "upgrade observer image"
	tWaitOBServerPodReady         ttypes.TaskName = "wait observer pod ready"
	tWaitOBServerActiveInCluster  ttypes.TaskName = "wait observer active in cluster"
	tWaitOBServerDeletedInCluster ttypes.TaskName = "wait observer deleted in cluster"
	tDeletePod                    ttypes.TaskName = "delete pod"
	tWaitForPodDeleted            ttypes.TaskName = "wait for pod deleted"
	tExpandPVC                    ttypes.TaskName = "expand pvc"
	tWaitForPvcResized            ttypes.TaskName = "wait for pvc resized"
	tCreateOBServerSvc            ttypes.TaskName = "create observer svc"
)
