// Code generated by go generate; DO NOT EDIT.
package obproxy

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tCopyProxyROSecret       ttypes.TaskName = "copy proxy rosecret"
	tCreateOBProxyConfigMap  ttypes.TaskName = "create obproxy config map"
	tCreateOBProxyService    ttypes.TaskName = "create obproxy service"
	tCreateOBProxyDeployment ttypes.TaskName = "create obproxy deployment"
	tWaitOBProxyReady        ttypes.TaskName = "wait obproxy ready"
	tUpdateOBProxyConfigMap  ttypes.TaskName = "update obproxy config map"
	tUpdateOBProxyDeployment ttypes.TaskName = "update obproxy deployment"
tScaleOBProxyDeployment  ttypes.TaskName = "scale obproxy deployment"
	tDeleteOBProxyDeployment ttypes.TaskName = "delete obproxy deployment"
	tDeleteOBProxyService    ttypes.TaskName = "delete obproxy service"
	tDeleteOBProxyConfigMap  ttypes.TaskName = "delete obproxy config map"
	tDeleteOBProxySecrets    ttypes.TaskName = "delete obproxy secrets"
)
