// Code generated by go generate; DO NOT EDIT.
package obproxy

func init() {
	taskMap.Register(tCopyProxyROSecret, CopyProxyROSecret)
	taskMap.Register(tCreateOBProxyConfigMap, CreateOBProxyConfigMap)
	taskMap.Register(tCreateOBProxyService, CreateOBProxyService)
	taskMap.Register(tCreateOBProxyDeployment, CreateOBProxyDeployment)
	taskMap.Register(tWaitOBProxyReady, WaitOBProxyReady)
	taskMap.Register(tUpdateOBProxyConfigMap, UpdateOBProxyConfigMap)
	taskMap.Register(tUpdateOBProxyDeployment, UpdateOBProxyDeployment)
taskMap.Register(tScaleOBProxyDeployment, ScaleOBProxyDeployment)
	taskMap.Register(tDeleteOBProxyDeployment, DeleteOBProxyDeployment)
	taskMap.Register(tDeleteOBProxyService, DeleteOBProxyService)
	taskMap.Register(tDeleteOBProxyConfigMap, DeleteOBProxyConfigMap)
	taskMap.Register(tDeleteOBProxySecrets, DeleteOBProxySecrets)
}
