apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenantOperation
metadata:
  name: op-chg-pwd
  namespace: oceanbase
spec:
  type: "CHANGE_PASSWORD"
  changePwd:
    tenant: "t1"
    secretRef: "t1-credential-new"