/* tslint:disable */
/* eslint-disable */
/**
 * OceanBase Dashboard API
 * OceanBase Dashboard
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  ClusterApiFactory,
  Configuration,
  InfoApiFactory,
  OBClusterApiFactory,
  OBTenantApiFactory,
  TerminalApiFactory,
  UserApiFactory,
} from './generated/index';

const config = new Configuration({
  basePath:
    process.env.NODE_ENV === 'development' ? 'http://localhost:8000' : '/',
  apiKey: (_: string) => document.cookie,
  baseOptions: {
    withCredentials: true,
  },
});

export const info = InfoApiFactory(config);
export const cluster = ClusterApiFactory(config);
export const obcluster = OBClusterApiFactory(config);
export const obtenant = OBTenantApiFactory(config);
export const terminal = TerminalApiFactory(config);
export const user = UserApiFactory(config);
