name:
obcluster:
replicas: 2
image: oceanbase/obproxy-ce:4.3.3.0-5

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 512Mi

service:
  type: ClusterIP

# parameters:
#   mysql_version: 8.0.30
