version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - errcheck
    - gocritic
    # - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    # - unused

  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
    revive:
      enable-all-rules: true
      rules:
        - name: struct-tag
          disabled: true
        - name: var-naming
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: exported
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: file-header
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: argument-limit
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: confusing-results
          disabled: true
        - name: add-constant
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: nested-structs
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: early-return
          disabled: true
        - name: deep-exit
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/oceanbase/ob-operator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - revive
        - unused