// Code generated by go generate; DO NOT EDIT.
package oblogservicenode

func init() {
	taskMap.Register(tCreatePod, CreatePod)
	taskMap.Register(tWaitPodReady, WaitPodReady)
	taskMap.Register(tDeletePod, DeletePod)
}
