// Code generated by go generate; DO NOT EDIT.
package oblogservicenode

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tCreatePod    ttypes.TaskName = "create log service node pod"
	tWaitPodReady ttypes.TaskName = "wait log service node pod ready"
	tDeletePod    ttypes.TaskName = "delete log service node pod"
)
