// Code generated by go generate; DO NOT EDIT.
package oblogservicenode

func init() {
	taskMap.Register(tCreateSvc, CreateSvc)
	taskMap.Register(tCreatePVC, CreatePVC)
	taskMap.Register(tCreatePod, CreatePod)
	taskMap.Register(tWaitPodReady, WaitPodReady)
	taskMap.Register(tWaitClusterBootstrapped, WaitClusterBootstrapped)
	taskMap.Register(tDeletePod, DeletePod)
}
