// Code generated by go generate; DO NOT EDIT.
package oblogservicenode

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tCreatePod    ttypes.TaskName = "create pod"
	tWaitPodReady ttypes.TaskName = "wait pod ready"
	tDeletePod    ttypes.TaskName = "delete pod"
)
