// Code generated by go generate; DO NOT EDIT.
package oblogservicenode

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tCreateSvc               ttypes.TaskName = "create svc"
	tCreatePVC               ttypes.TaskName = "create pvc"
	tCreatePod               ttypes.TaskName = "create pod"
	tWaitPodReady            ttypes.TaskName = "wait pod ready"
	tWaitClusterBootstrapped ttypes.TaskName = "wait cluster bootstrapped"
	tDeletePod               ttypes.TaskName = "delete pod"
	tWaitPodDeleted          ttypes.TaskName = "wait pod deleted"
)
