// Code generated by go generate; DO NOT EDIT.
package obclusteroperation

func init() {
	taskMap.Register(tModifyClusterSpec, ModifyClusterSpec)
	taskMap.Register(tWaitForCluster, WaitForCluster)
	taskMap.Register(tRestartServers, RestartServers)
}
