// Code generated by go generate; DO NOT EDIT.
package obclusteroperation

func init() {
	taskMap.Register(tModifyClusterSpec, ModifyClusterSpec)
	taskMap.Register(tWaitForClusterReturnRunning, WaitForClusterReturnRunning)
	taskMap.Register(tAnnotateOBServersForDeletion, AnnotateOBServersForDeletion)
	taskMap.Register(tRestartOBServers, RestartOBServers)
}
