apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenantBackupPolicy
metadata:
  name: obtenantbackuppolicy-oss
  # namespace: oceanbase
spec:
  obClusterName: "obcluster"
  tenantName: "t1"
  tenantSecret: "t1-ro"
  jobKeepWindow: "1d"
  dataClean:
    recoveryWindow: "8d"
  logArchive:
    destination:
      type: "OSS"
      path: "oss://operator-backup-data/archive-t1-1128?host=oss-cn-hangzhou.aliyuncs.com"
      ossAccessSecret: "oss-access"
    switchPieceInterval: "1d"
  dataBackup:
    destination:
      type: "OSS"
      path: "oss://operator-backup-data/backup-t1-1128?host=oss-cn-hangzhou.aliyuncs.com"
      ossAccessSecret: "oss-access"
    fullCrontab: "30 0 * * 6"
    incrementalCrontab: "*/10 * * * *"
