apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenantBackupPolicy
metadata:
  name: obtenantbackuppolicy-sample
  namespace: oceanbase
spec:
  obClusterName: "test"
  tenantCRName: "t1"
  jobKeepWindow: "1d"
  dataClean:
    recoveryWindow: "8d"
  logArchive:
    destination:
      type: "NFS"
      path: "t1/log_archive_custom_1019"
    switchPieceInterval: "1d"
  dataBackup:
    destination:
      type: "NFS"
      path: "t1/data_backup_custom_enc"
    fullCrontab: "30 0 * * 6"
    incrementalCrontab: "30 1 * * *"