apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenant
metadata:
  name: sysbenchtenant
  namespace: oceanbase
spec:
  obcluster: sysbenchcluster
  tenantName: sysbenchtenant
  credentials:
    root: sc-tenant-root
    standbyRo: sc-tenant-standbyro
  unitNum: 1
  charset: utf8mb4
  connectWhiteList: '%'
  forceDelete: true
  pools:
    - zone: zone1
      type:
        name: Full
        replica: 1
        isActive: true
      resource:
        maxCPU: 4
        memorySize: 7.5Gi
    - zone: zone2
      type:
        name: Full
        replica: 1
        isActive: true
      resource:
        maxCPU: 4
        memorySize: 7.5Gi
    - zone: zone3
      type:
        name: Full
        replica: 1
        isActive: true
      resource:
        maxCPU: 4
        memorySize: 7.5Gi
