// Code generated by go generate; DO NOT EDIT.
package obtenantvariable

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tSetOBTenantVariable ttypes.TaskName = "set obtenant variable"
)
