#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep "ui/" || true) 
if [ -n "$CHANGED_FILES" ]; then
  cd ui && npm run check-style && npm run lint
fi
exit 0