apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBTenant
metadata:
  name: t1
  namespace: default
spec:
  obcluster: test
  tenantName: t1
  unitNum: 1
  charset: utf8mb4
  connectWhiteList: "%"
  forceDelete: true
  pools:
    - zone: zone1
      type:
        name: Full
        replica: 1
        isActive: true
      resource:
        maxCPU: 1
        memorySize: 2Gi
        minCPU: 1
        maxIops: 1024
        minIops: 1024
        iopsWeight: 2
        logDiskSize: 4Gi
