# permissions for end users to view obclusteroperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: obclusteroperation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ob-operator
    app.kubernetes.io/part-of: ob-operator
    app.kubernetes.io/managed-by: kustomize
  name: obclusteroperation-viewer-role
rules:
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obclusteroperations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obclusteroperations/status
  verbs:
  - get
