# permissions for end users to edit obtenantoperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: obtenantoperation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ob-operator
    app.kubernetes.io/part-of: ob-operator
    app.kubernetes.io/managed-by: kustomize
  name: obtenantoperation-editor-role
rules:
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obtenantoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obtenantoperations/status
  verbs:
  - get
