# permissions for end users to view obtenantbackuppolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: obtenantbackuppolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ob-operator
    app.kubernetes.io/part-of: ob-operator
    app.kubernetes.io/managed-by: kustomize
  name: obtenantbackuppolicy-viewer-role
rules:
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obtenantbackuppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obtenantbackuppolicies/status
  verbs:
  - get
