# permissions for end users to edit obtenantvariables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ob-operator
    app.kubernetes.io/managed-by: kustomize
  name: obtenantvariable-editor-role
rules:
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obtenantvariables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oceanbase.oceanbase.com
  resources:
  - obtenantvariables/status
  verbs:
  - get
