apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "obproxy-ce.labels" . | nindent 4 }}
spec:
  ports:
  - name: sql
    port: 2883
    protocol: TCP
    targetPort: 2883
  - name: prometheus
    port: 2884
    protocol: TCP
    targetPort: 2884
  selector:
    app: obproxy-{{ .Release.Name }}
  type: {{ .Values.service.type }}
