apiVersion: cloud.oceanbase.com/v1
kind: OBCluster
metadata:
  name: ob-test
spec:
  imageRepo: oceanbase/oceanbase-cloud-native
  tag: 4.1.0.1-102000042023061314
  imageObagent: oceanbase/obagent:1.2.0
  clusterID: 1
  topology:
    - cluster: cn
      zone:
      - name: zone1
        region: region1
        nodeSelector:
          ob.zone: test
        replicas: 1
      parameters:
        - name: system_memory
          value: "1G"
        - name: log_disk_size
          value: "40G"
  resources:
    cpu: 2
    memory: 10Gi
    storage:
      - name: data-file
        storageClassName: "local-path"
        size: 50Gi
      - name: data-log
        storageClassName: "local-path"
        size: 50Gi
      - name: log
        storageClassName: "local-path"
        size: 30Gi
      - name: obagent-conf-file
        storageClassName: "local-path"
        size: 1Gi
