//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/oceanbase/ob-operator/api/types"
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlterZoneReplicas) DeepCopyInto(out *AlterZoneReplicas) {
	*out = *in
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlterZoneReplicas.
func (in *AlterZoneReplicas) DeepCopy() *AlterZoneReplicas {
	if in == nil {
		return nil
	}
	out := new(AlterZoneReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanPolicy) DeepCopyInto(out *CleanPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanPolicy.
func (in *CleanPolicy) DeepCopy() *CleanPolicy {
	if in == nil {
		return nil
	}
	out := new(CleanPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataBackupConfig) DeepCopyInto(out *DataBackupConfig) {
	*out = *in
	out.Destination = in.Destination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataBackupConfig.
func (in *DataBackupConfig) DeepCopy() *DataBackupConfig {
	if in == nil {
		return nil
	}
	out := new(DataBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteOBServersConfig) DeepCopyInto(out *DeleteOBServersConfig) {
	*out = *in
	if in.OBServers != nil {
		in, out := &in.OBServers, &out.OBServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteOBServersConfig.
func (in *DeleteOBServersConfig) DeepCopy() *DeleteOBServersConfig {
	if in == nil {
		return nil
	}
	out := new(DeleteOBServersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpandStorageSizeConfig) DeepCopyInto(out *ExpandStorageSizeConfig) {
	*out = *in
	if in.DataStorage != nil {
		in, out := &in.DataStorage, &out.DataStorage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.LogStorage != nil {
		in, out := &in.LogStorage, &out.LogStorage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.RedoLogStorage != nil {
		in, out := &in.RedoLogStorage, &out.RedoLogStorage
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpandStorageSizeConfig.
func (in *ExpandStorageSizeConfig) DeepCopy() *ExpandStorageSizeConfig {
	if in == nil {
		return nil
	}
	out := new(ExpandStorageSizeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalityType) DeepCopyInto(out *LocalityType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalityType.
func (in *LocalityType) DeepCopy() *LocalityType {
	if in == nil {
		return nil
	}
	out := new(LocalityType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogArchiveConfig) DeepCopyInto(out *LogArchiveConfig) {
	*out = *in
	out.Destination = in.Destination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogArchiveConfig.
func (in *LogArchiveConfig) DeepCopy() *LogArchiveConfig {
	if in == nil {
		return nil
	}
	out := new(LogArchiveConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrateServerStatus) DeepCopyInto(out *MigrateServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrateServerStatus.
func (in *MigrateServerStatus) DeepCopy() *MigrateServerStatus {
	if in == nil {
		return nil
	}
	out := new(MigrateServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifyOBServersConfig) DeepCopyInto(out *ModifyOBServersConfig) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = (*in).DeepCopy()
	}
	if in.ExpandStorageSize != nil {
		in, out := &in.ExpandStorageSize, &out.ExpandStorageSize
		*out = new(ExpandStorageSizeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ModifyStorageClass != nil {
		in, out := &in.ModifyStorageClass, &out.ModifyStorageClass
		*out = new(ModifyStorageClassConfig)
		**out = **in
	}
	if in.AddingMonitor != nil {
		in, out := &in.AddingMonitor, &out.AddingMonitor
		*out = (*in).DeepCopy()
	}
	if in.AddingBackupVolume != nil {
		in, out := &in.AddingBackupVolume, &out.AddingBackupVolume
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifyOBServersConfig.
func (in *ModifyOBServersConfig) DeepCopy() *ModifyOBServersConfig {
	if in == nil {
		return nil
	}
	out := new(ModifyOBServersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifyStorageClassConfig) DeepCopyInto(out *ModifyStorageClassConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifyStorageClassConfig.
func (in *ModifyStorageClassConfig) DeepCopy() *ModifyStorageClassConfig {
	if in == nil {
		return nil
	}
	out := new(ModifyStorageClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBCluster) DeepCopyInto(out *OBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBCluster.
func (in *OBCluster) DeepCopy() *OBCluster {
	if in == nil {
		return nil
	}
	out := new(OBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBClusterList) DeepCopyInto(out *OBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBClusterList.
func (in *OBClusterList) DeepCopy() *OBClusterList {
	if in == nil {
		return nil
	}
	out := new(OBClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBClusterOperation) DeepCopyInto(out *OBClusterOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBClusterOperation.
func (in *OBClusterOperation) DeepCopy() *OBClusterOperation {
	if in == nil {
		return nil
	}
	out := new(OBClusterOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBClusterOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBClusterOperationList) DeepCopyInto(out *OBClusterOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBClusterOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBClusterOperationList.
func (in *OBClusterOperationList) DeepCopy() *OBClusterOperationList {
	if in == nil {
		return nil
	}
	out := new(OBClusterOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBClusterOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBClusterOperationSpec) DeepCopyInto(out *OBClusterOperationSpec) {
	*out = *in
	if in.AddZones != nil {
		in, out := &in.AddZones, &out.AddZones
		*out = make([]types.OBZoneTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeleteZones != nil {
		in, out := &in.DeleteZones, &out.DeleteZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdjustReplicas != nil {
		in, out := &in.AdjustReplicas, &out.AdjustReplicas
		*out = make([]AlterZoneReplicas, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeleteOBServers != nil {
		in, out := &in.DeleteOBServers, &out.DeleteOBServers
		*out = new(DeleteOBServersConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RestartOBServers != nil {
		in, out := &in.RestartOBServers, &out.RestartOBServers
		*out = new(RestartOBServersConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(UpgradeConfig)
		**out = **in
	}
	if in.ModifyOBServers != nil {
		in, out := &in.ModifyOBServers, &out.ModifyOBServers
		*out = new(ModifyOBServersConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SetParameters != nil {
		in, out := &in.SetParameters, &out.SetParameters
		*out = make([]types.Parameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBClusterOperationSpec.
func (in *OBClusterOperationSpec) DeepCopy() *OBClusterOperationSpec {
	if in == nil {
		return nil
	}
	out := new(OBClusterOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBClusterOperationStatus) DeepCopyInto(out *OBClusterOperationStatus) {
	*out = *in
	if in.OperationContext != nil {
		in, out := &in.OperationContext, &out.OperationContext
		*out = (*in).DeepCopy()
	}
	if in.ClusterSnapshot != nil {
		in, out := &in.ClusterSnapshot, &out.ClusterSnapshot
		*out = new(OBClusterSnapshot)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBClusterOperationStatus.
func (in *OBClusterOperationStatus) DeepCopy() *OBClusterOperationStatus {
	if in == nil {
		return nil
	}
	out := new(OBClusterOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBClusterSnapshot) DeepCopyInto(out *OBClusterSnapshot) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(OBClusterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(OBClusterStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBClusterSnapshot.
func (in *OBClusterSnapshot) DeepCopy() *OBClusterSnapshot {
	if in == nil {
		return nil
	}
	out := new(OBClusterSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBClusterSpec) DeepCopyInto(out *OBClusterSpec) {
	*out = *in
	if in.OBServerTemplate != nil {
		in, out := &in.OBServerTemplate, &out.OBServerTemplate
		*out = (*in).DeepCopy()
	}
	if in.MonitorTemplate != nil {
		in, out := &in.MonitorTemplate, &out.MonitorTemplate
		*out = (*in).DeepCopy()
	}
	if in.BackupVolume != nil {
		in, out := &in.BackupVolume, &out.BackupVolume
		*out = (*in).DeepCopy()
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]types.Parameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]types.OBZoneTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserSecrets != nil {
		in, out := &in.UserSecrets, &out.UserSecrets
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBClusterSpec.
func (in *OBClusterSpec) DeepCopy() *OBClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBClusterStatus) DeepCopyInto(out *OBClusterStatus) {
	*out = *in
	if in.OperationContext != nil {
		in, out := &in.OperationContext, &out.OperationContext
		*out = (*in).DeepCopy()
	}
	if in.OBZoneStatus != nil {
		in, out := &in.OBZoneStatus, &out.OBZoneStatus
		*out = make([]types.OBZoneReplicaStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]types.Parameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBClusterStatus.
func (in *OBClusterStatus) DeepCopy() *OBClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBParameter) DeepCopyInto(out *OBParameter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBParameter.
func (in *OBParameter) DeepCopy() *OBParameter {
	if in == nil {
		return nil
	}
	out := new(OBParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBParameter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBParameterList) DeepCopyInto(out *OBParameterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBParameterList.
func (in *OBParameterList) DeepCopy() *OBParameterList {
	if in == nil {
		return nil
	}
	out := new(OBParameterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBParameterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBParameterSpec) DeepCopyInto(out *OBParameterSpec) {
	*out = *in
	if in.Parameter != nil {
		in, out := &in.Parameter, &out.Parameter
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBParameterSpec.
func (in *OBParameterSpec) DeepCopy() *OBParameterSpec {
	if in == nil {
		return nil
	}
	out := new(OBParameterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBParameterStatus) DeepCopyInto(out *OBParameterStatus) {
	*out = *in
	if in.OperationContext != nil {
		in, out := &in.OperationContext, &out.OperationContext
		*out = (*in).DeepCopy()
	}
	if in.Parameter != nil {
		in, out := &in.Parameter, &out.Parameter
		*out = make([]types.ParameterValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBParameterStatus.
func (in *OBParameterStatus) DeepCopy() *OBParameterStatus {
	if in == nil {
		return nil
	}
	out := new(OBParameterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBResourceRescue) DeepCopyInto(out *OBResourceRescue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBResourceRescue.
func (in *OBResourceRescue) DeepCopy() *OBResourceRescue {
	if in == nil {
		return nil
	}
	out := new(OBResourceRescue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBResourceRescue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBResourceRescueList) DeepCopyInto(out *OBResourceRescueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBResourceRescue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBResourceRescueList.
func (in *OBResourceRescueList) DeepCopy() *OBResourceRescueList {
	if in == nil {
		return nil
	}
	out := new(OBResourceRescueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBResourceRescueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBResourceRescueSpec) DeepCopyInto(out *OBResourceRescueSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBResourceRescueSpec.
func (in *OBResourceRescueSpec) DeepCopy() *OBResourceRescueSpec {
	if in == nil {
		return nil
	}
	out := new(OBResourceRescueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBResourceRescueStatus) DeepCopyInto(out *OBResourceRescueStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBResourceRescueStatus.
func (in *OBResourceRescueStatus) DeepCopy() *OBResourceRescueStatus {
	if in == nil {
		return nil
	}
	out := new(OBResourceRescueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBServer) DeepCopyInto(out *OBServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBServer.
func (in *OBServer) DeepCopy() *OBServer {
	if in == nil {
		return nil
	}
	out := new(OBServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBServerList) DeepCopyInto(out *OBServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBServerList.
func (in *OBServerList) DeepCopy() *OBServerList {
	if in == nil {
		return nil
	}
	out := new(OBServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBServerSpec) DeepCopyInto(out *OBServerSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OBServerTemplate != nil {
		in, out := &in.OBServerTemplate, &out.OBServerTemplate
		*out = (*in).DeepCopy()
	}
	if in.MonitorTemplate != nil {
		in, out := &in.MonitorTemplate, &out.MonitorTemplate
		*out = (*in).DeepCopy()
	}
	if in.BackupVolume != nil {
		in, out := &in.BackupVolume, &out.BackupVolume
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBServerSpec.
func (in *OBServerSpec) DeepCopy() *OBServerSpec {
	if in == nil {
		return nil
	}
	out := new(OBServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBServerStatus) DeepCopyInto(out *OBServerStatus) {
	*out = *in
	if in.OperationContext != nil {
		in, out := &in.OperationContext, &out.OperationContext
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBServerStatus.
func (in *OBServerStatus) DeepCopy() *OBServerStatus {
	if in == nil {
		return nil
	}
	out := new(OBServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenant) DeepCopyInto(out *OBTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenant.
func (in *OBTenant) DeepCopy() *OBTenant {
	if in == nil {
		return nil
	}
	out := new(OBTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantBackup) DeepCopyInto(out *OBTenantBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantBackup.
func (in *OBTenantBackup) DeepCopy() *OBTenantBackup {
	if in == nil {
		return nil
	}
	out := new(OBTenantBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantBackupList) DeepCopyInto(out *OBTenantBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBTenantBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantBackupList.
func (in *OBTenantBackupList) DeepCopy() *OBTenantBackupList {
	if in == nil {
		return nil
	}
	out := new(OBTenantBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantBackupPolicy) DeepCopyInto(out *OBTenantBackupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantBackupPolicy.
func (in *OBTenantBackupPolicy) DeepCopy() *OBTenantBackupPolicy {
	if in == nil {
		return nil
	}
	out := new(OBTenantBackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantBackupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantBackupPolicyList) DeepCopyInto(out *OBTenantBackupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBTenantBackupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantBackupPolicyList.
func (in *OBTenantBackupPolicyList) DeepCopy() *OBTenantBackupPolicyList {
	if in == nil {
		return nil
	}
	out := new(OBTenantBackupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantBackupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantBackupPolicySpec) DeepCopyInto(out *OBTenantBackupPolicySpec) {
	*out = *in
	out.LogArchive = in.LogArchive
	out.DataBackup = in.DataBackup
	out.DataClean = in.DataClean
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantBackupPolicySpec.
func (in *OBTenantBackupPolicySpec) DeepCopy() *OBTenantBackupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantBackupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantBackupSpec) DeepCopyInto(out *OBTenantBackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantBackupSpec.
func (in *OBTenantBackupSpec) DeepCopy() *OBTenantBackupSpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantList) DeepCopyInto(out *OBTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantList.
func (in *OBTenantList) DeepCopy() *OBTenantList {
	if in == nil {
		return nil
	}
	out := new(OBTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantOpChangePwdSpec) DeepCopyInto(out *OBTenantOpChangePwdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantOpChangePwdSpec.
func (in *OBTenantOpChangePwdSpec) DeepCopy() *OBTenantOpChangePwdSpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantOpChangePwdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantOpFailoverSpec) DeepCopyInto(out *OBTenantOpFailoverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantOpFailoverSpec.
func (in *OBTenantOpFailoverSpec) DeepCopy() *OBTenantOpFailoverSpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantOpFailoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantOpSwitchoverSpec) DeepCopyInto(out *OBTenantOpSwitchoverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantOpSwitchoverSpec.
func (in *OBTenantOpSwitchoverSpec) DeepCopy() *OBTenantOpSwitchoverSpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantOpSwitchoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantOperation) DeepCopyInto(out *OBTenantOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantOperation.
func (in *OBTenantOperation) DeepCopy() *OBTenantOperation {
	if in == nil {
		return nil
	}
	out := new(OBTenantOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantOperationList) DeepCopyInto(out *OBTenantOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBTenantOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantOperationList.
func (in *OBTenantOperationList) DeepCopy() *OBTenantOperationList {
	if in == nil {
		return nil
	}
	out := new(OBTenantOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantOperationSpec) DeepCopyInto(out *OBTenantOperationSpec) {
	*out = *in
	if in.Switchover != nil {
		in, out := &in.Switchover, &out.Switchover
		*out = new(OBTenantOpSwitchoverSpec)
		**out = **in
	}
	if in.Failover != nil {
		in, out := &in.Failover, &out.Failover
		*out = new(OBTenantOpFailoverSpec)
		**out = **in
	}
	if in.ChangePwd != nil {
		in, out := &in.ChangePwd, &out.ChangePwd
		*out = new(OBTenantOpChangePwdSpec)
		**out = **in
	}
	if in.ReplayUntil != nil {
		in, out := &in.ReplayUntil, &out.ReplayUntil
		*out = new(RestoreUntilConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetTenant != nil {
		in, out := &in.TargetTenant, &out.TargetTenant
		*out = new(string)
		**out = **in
	}
	if in.AuxiliaryTenant != nil {
		in, out := &in.AuxiliaryTenant, &out.AuxiliaryTenant
		*out = new(string)
		**out = **in
	}
	if in.ModifyResourcePools != nil {
		in, out := &in.ModifyResourcePools, &out.ModifyResourcePools
		*out = make([]ResourcePoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AddResourcePools != nil {
		in, out := &in.AddResourcePools, &out.AddResourcePools
		*out = make([]ResourcePoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeleteResourcePools != nil {
		in, out := &in.DeleteResourcePools, &out.DeleteResourcePools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantOperationSpec.
func (in *OBTenantOperationSpec) DeepCopy() *OBTenantOperationSpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantOperationStatus) DeepCopyInto(out *OBTenantOperationStatus) {
	*out = *in
	if in.OperationContext != nil {
		in, out := &in.OperationContext, &out.OperationContext
		*out = (*in).DeepCopy()
	}
	if in.PrimaryTenant != nil {
		in, out := &in.PrimaryTenant, &out.PrimaryTenant
		*out = new(OBTenant)
		(*in).DeepCopyInto(*out)
	}
	if in.SecondaryTenant != nil {
		in, out := &in.SecondaryTenant, &out.SecondaryTenant
		*out = new(OBTenant)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantOperationStatus.
func (in *OBTenantOperationStatus) DeepCopy() *OBTenantOperationStatus {
	if in == nil {
		return nil
	}
	out := new(OBTenantOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantRestore) DeepCopyInto(out *OBTenantRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantRestore.
func (in *OBTenantRestore) DeepCopy() *OBTenantRestore {
	if in == nil {
		return nil
	}
	out := new(OBTenantRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantRestoreList) DeepCopyInto(out *OBTenantRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBTenantRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantRestoreList.
func (in *OBTenantRestoreList) DeepCopy() *OBTenantRestoreList {
	if in == nil {
		return nil
	}
	out := new(OBTenantRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantRestoreSpec) DeepCopyInto(out *OBTenantRestoreSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.PrimaryTenant != nil {
		in, out := &in.PrimaryTenant, &out.PrimaryTenant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantRestoreSpec.
func (in *OBTenantRestoreSpec) DeepCopy() *OBTenantRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantSpec) DeepCopyInto(out *OBTenantSpec) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]ResourcePoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(TenantSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantSpec.
func (in *OBTenantSpec) DeepCopy() *OBTenantSpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantVariable) DeepCopyInto(out *OBTenantVariable) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantVariable.
func (in *OBTenantVariable) DeepCopy() *OBTenantVariable {
	if in == nil {
		return nil
	}
	out := new(OBTenantVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantVariable) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantVariableList) DeepCopyInto(out *OBTenantVariableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBTenantVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantVariableList.
func (in *OBTenantVariableList) DeepCopy() *OBTenantVariableList {
	if in == nil {
		return nil
	}
	out := new(OBTenantVariableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBTenantVariableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantVariableSpec) DeepCopyInto(out *OBTenantVariableSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantVariableSpec.
func (in *OBTenantVariableSpec) DeepCopy() *OBTenantVariableSpec {
	if in == nil {
		return nil
	}
	out := new(OBTenantVariableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBTenantVariableStatus) DeepCopyInto(out *OBTenantVariableStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBTenantVariableStatus.
func (in *OBTenantVariableStatus) DeepCopy() *OBTenantVariableStatus {
	if in == nil {
		return nil
	}
	out := new(OBTenantVariableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBZone) DeepCopyInto(out *OBZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBZone.
func (in *OBZone) DeepCopy() *OBZone {
	if in == nil {
		return nil
	}
	out := new(OBZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBZoneList) DeepCopyInto(out *OBZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OBZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBZoneList.
func (in *OBZoneList) DeepCopy() *OBZoneList {
	if in == nil {
		return nil
	}
	out := new(OBZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OBZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBZoneSpec) DeepCopyInto(out *OBZoneSpec) {
	*out = *in
	in.Topology.DeepCopyInto(&out.Topology)
	if in.OBServerTemplate != nil {
		in, out := &in.OBServerTemplate, &out.OBServerTemplate
		*out = (*in).DeepCopy()
	}
	if in.MonitorTemplate != nil {
		in, out := &in.MonitorTemplate, &out.MonitorTemplate
		*out = (*in).DeepCopy()
	}
	if in.BackupVolume != nil {
		in, out := &in.BackupVolume, &out.BackupVolume
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBZoneSpec.
func (in *OBZoneSpec) DeepCopy() *OBZoneSpec {
	if in == nil {
		return nil
	}
	out := new(OBZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OBZoneStatus) DeepCopyInto(out *OBZoneStatus) {
	*out = *in
	if in.OperationContext != nil {
		in, out := &in.OperationContext, &out.OperationContext
		*out = (*in).DeepCopy()
	}
	if in.OBServerStatus != nil {
		in, out := &in.OBServerStatus, &out.OBServerStatus
		*out = make([]types.OBServerReplicaStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OBZoneStatus.
func (in *OBZoneStatus) DeepCopy() *OBZoneStatus {
	if in == nil {
		return nil
	}
	out := new(OBZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePoolSpec) DeepCopyInto(out *ResourcePoolSpec) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(LocalityType)
		**out = **in
	}
	if in.UnitConfig != nil {
		in, out := &in.UnitConfig, &out.UnitConfig
		*out = new(UnitConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePoolSpec.
func (in *ResourcePoolSpec) DeepCopy() *ResourcePoolSpec {
	if in == nil {
		return nil
	}
	out := new(ResourcePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePoolStatus) DeepCopyInto(out *ResourcePoolStatus) {
	*out = *in
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = make([]UnitStatus, len(*in))
		copy(*out, *in)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(LocalityType)
		**out = **in
	}
	if in.UnitConfig != nil {
		in, out := &in.UnitConfig, &out.UnitConfig
		*out = new(UnitConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePoolStatus.
func (in *ResourcePoolStatus) DeepCopy() *ResourcePoolStatus {
	if in == nil {
		return nil
	}
	out := new(ResourcePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartOBServersConfig) DeepCopyInto(out *RestartOBServersConfig) {
	*out = *in
	if in.OBServers != nil {
		in, out := &in.OBServers, &out.OBServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OBZones != nil {
		in, out := &in.OBZones, &out.OBZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartOBServersConfig.
func (in *RestartOBServersConfig) DeepCopy() *RestartOBServersConfig {
	if in == nil {
		return nil
	}
	out := new(RestartOBServersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSourceSpec) DeepCopyInto(out *RestoreSourceSpec) {
	*out = *in
	if in.ArchiveSource != nil {
		in, out := &in.ArchiveSource, &out.ArchiveSource
		*out = new(types.BackupDestination)
		**out = **in
	}
	if in.BakDataSource != nil {
		in, out := &in.BakDataSource, &out.BakDataSource
		*out = new(types.BackupDestination)
		**out = **in
	}
	in.Until.DeepCopyInto(&out.Until)
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ReplayLogUntil != nil {
		in, out := &in.ReplayLogUntil, &out.ReplayLogUntil
		*out = new(RestoreUntilConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSourceSpec.
func (in *RestoreSourceSpec) DeepCopy() *RestoreSourceSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreUntilConfig) DeepCopyInto(out *RestoreUntilConfig) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(string)
		**out = **in
	}
	if in.Scn != nil {
		in, out := &in.Scn, &out.Scn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreUntilConfig.
func (in *RestoreUntilConfig) DeepCopy() *RestoreUntilConfig {
	if in == nil {
		return nil
	}
	out := new(RestoreUntilConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCredentials) DeepCopyInto(out *TenantCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCredentials.
func (in *TenantCredentials) DeepCopy() *TenantCredentials {
	if in == nil {
		return nil
	}
	out := new(TenantCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantRecordInfo) DeepCopyInto(out *TenantRecordInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantRecordInfo.
func (in *TenantRecordInfo) DeepCopy() *TenantRecordInfo {
	if in == nil {
		return nil
	}
	out := new(TenantRecordInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSourceSpec) DeepCopyInto(out *TenantSourceSpec) {
	*out = *in
	if in.Tenant != nil {
		in, out := &in.Tenant, &out.Tenant
		*out = new(string)
		**out = **in
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreSourceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSourceSpec.
func (in *TenantSourceSpec) DeepCopy() *TenantSourceSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSourceStatus.
func (in *TenantSourceStatus) DeepCopy() *TenantSourceStatus {
	if in == nil {
		return nil
	}
	out := new(TenantSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnitConfig) DeepCopyInto(out *UnitConfig) {
	*out = *in
	out.MaxCPU = in.MaxCPU.DeepCopy()
	out.MemorySize = in.MemorySize.DeepCopy()
	out.MinCPU = in.MinCPU.DeepCopy()
	out.LogDiskSize = in.LogDiskSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnitConfig.
func (in *UnitConfig) DeepCopy() *UnitConfig {
	if in == nil {
		return nil
	}
	out := new(UnitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnitStatus) DeepCopyInto(out *UnitStatus) {
	*out = *in
	out.Migrate = in.Migrate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnitStatus.
func (in *UnitStatus) DeepCopy() *UnitStatus {
	if in == nil {
		return nil
	}
	out := new(UnitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeConfig) DeepCopyInto(out *UpgradeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeConfig.
func (in *UpgradeConfig) DeepCopy() *UpgradeConfig {
	if in == nil {
		return nil
	}
	out := new(UpgradeConfig)
	in.DeepCopyInto(out)
	return out
}
