// Code generated by go generate; DO NOT EDIT.
package obtenantbackup

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tCreateBackupJobInOB ttypes.TaskName = "create backup job in ob"
)
