// Code generated by go generate; DO NOT EDIT.
package oblogservicecluster

func init() {
	taskMap.Register(tCreateZones, CreateZones)
	taskMap.Register(tWaitZonesBootstrapReady, WaitZonesBootstrapReady)
	taskMap.Register(tWaitZonesRunning, WaitZonesRunning)
	taskMap.Register(tBootstrapLogService, BootstrapLogService)
	taskMap.Register(tMarkNodesRegistered, MarkNodesRegistered)
	taskMap.Register(tModifyZoneReplica, ModifyZoneReplica)
}
