apiVersion: v1
kind: Service
metadata:
  name: svc-ob-configserver
  namespace: oceanbase
spec:
  type: NodePort
  selector:
    app: ob-configserver
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ob-configserver
  namespace: oceanbase
spec:
  selector:
    matchLabels:
      app: ob-configserver
  replicas: 1
  template:
    metadata:
      labels:
        app: ob-configserver
    spec:
      containers:
        - name: ob-configserver
          image: oceanbase/ob-configserver:1.0.0-2
          ports:
            - containerPort: 8080
              name: "http"
          env:
            - name: DATABASE_TYPE
              value: mysql
            - name: SVC_ADDRESS
              value: $(SVC_OB_CONFIGSERVER_SERVICE_HOST)
            - name: SVC_PORT
              value: $(SVC_OB_CONFIGSERVER_SERVICE_PORT)
            - name: META_HOST
              value: $(SVC_MYSQL_SERVICE_HOST)
            - name: META_PORT
              value: $(SVC_MYSQL_SERVICE_PORT)
            - name: META_USER
              value: 'root'
            - name: META_PASSWORD
              value: '******'
            - name: META_DATABASE
              value: 'configserver'
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests:
              memory: 200Mi
              cpu: 100m
