apiVersion: v1
kind: Service
metadata:
  name: svc-obproxy
  namespace: oceanbase
spec:
  type: ClusterIP
  selector:
    app: obproxy
  ports:
    - name: "sql"
      port: 2883
      targetPort: 2883
    - name: "prometheus"
      port: 2884
      targetPort: 2884

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obproxy
  namespace: oceanbase
spec:
  selector:
    matchLabels:
      app: obproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: obproxy
    spec:
      containers:
        - name: obproxy
          image: oceanbase/obproxy-ce:4.2.1.0-11
          ports:
            - containerPort: 2883
              name: "sql"
            - containerPort: 2884
              name: "prometheus"
          env:
            - name: APP_NAME
              value: helloworld
            - name: OB_CLUSTER
              value: metadb
            - name: CONFIG_URL
              value: 'http://svc-ob-configserver.oceanbase.svc:8080/services?Action=GetObProxyConfig'
            # - name: RS_LIST   # CONFIG_URL and RS_LIST are mutually exclusive. 
            #   value: '******' # If you decide to use RS_LIST, the value should be get from SQL statement "SELECT GROUP_CONCAT(CONCAT(SVR_IP, ':', SQL_PORT) SEPARATOR ';') AS RS_LIST FROM oceanbase.DBA_OB_SERVERS;" by connecting the cluster through pods.
            #                   # The value should be like 'IP1:2881;IP2:2881;IP3:2881'
            - name: PROXYRO_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: sc-sys-proxyro
                  key: password
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests: 
              memory: 200Mi
              cpu: 200m
