apiVersion: v1
kind: Service
metadata:
  name: svc-oceanbase-todo
spec:
  type: NodePort
  selector:
    app: oceanbase-todo
  ports:
    - name: "http"
      port: 20031
      targetPort: 20031
      nodePort: 32080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceanbase-todo
spec:
  selector:
    matchLabels:
      app: oceanbase-todo
  replicas: 2
  template:
    metadata:
      labels:
        app: oceanbase-todo
    spec:
      containers:
        - name: oceanbase-todo
          image: oceanbase/oceanbase-todo
          imagePullPolicy: IfNotPresent
          ports:
            - name: "http"
              containerPort: 20031
          env:
            - name: DB_HOST
              value: $(SVC_OBPROXY_SERVICE_HOST)
            - name: DB_PORT
              value: $(SVC_OBPROXY_SERVICE_PORT_SQL)
            - name: DB_USER
              value: root@metatenant#metadb
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-metatenant-root
                  key: password
            - name: DB_DATABASE
              value: "dev"
            - name: LISTEN_PORT
              value: "20031"
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 200Mi
              cpu: 100m
