apiVersion: v1
kind: Service
metadata:
  name: svc-ocp
  namespace: oceanbase
spec:
  type: NodePort
  selector:
    app: ocp
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      nodePort: 32080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocp
  namespace: oceanbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp
  template:
    metadata:
      labels:
        app: ocp
    spec:
      containers:
      - env:
        - name: OCP_METADB_HOST
          value: $(SVC_OBPROXY_SERVICE_HOST)
        - name: OCP_METADB_PORT
          value: $(SVC_OBPROXY_SERVICE_PORT_SQL)
        - name: OCP_METADB_USER
          value: root@metatenant#metadb
        - name: OCP_METADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sc-metatenant-root
              key: password
        - name: OCP_METADB_DBNAME
          value: ocp_metadb
        - name: OCP_MONITORDB_USER
          value: root@metatenant#metadb
        - name: OCP_MONITORDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sc-metatenant-root
              key: password
        - name: OCP_MONITORDB_DBNAME
          value: ocp_monitordb
        - name: OCP_CURRENT_AZONE_NAME
          value: ocp_azone1
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: TERM
          value: xterm
        - name: OB_OPTS_MEM
          value: -Xms6g -Xmx6g -Xmn2g -XX:PermSize=128m -Xss512k
        - name: OB_PORT
          value: "8080"
        - name: obcluster_name
          value: metadb
        image: oceanbase/ocp-ce:4.2.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 100
          initialDelaySeconds: 600
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        name: ocp
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 80
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
          requests: 
            memory: 1Gi
            cpu: 500m
      restartPolicy: Always
