apiVersion: v1
kind: Service
metadata:
  name: odc
  namespace: oceanbase
spec:
  type: NodePort
  selector:
    app: odc
  ports:
    - name: "http"
      port: 8989
      targetPort: 8989
      nodePort: 30089

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odc
  namespace: oceanbase
spec:
  selector:
    matchLabels:
      app: odc
  replicas: 1
  template:
    metadata:
      labels:
        app: odc
    spec:
      containers:
        - name: odc
          image: oceanbase/odc:latest
          ports:
            - containerPort: 8989
              name: "http"
          env:
            - name: DATABASE_HOST
              value: $(SVC_OBPROXY_SERVICE_HOST)
            - name: DATABASE_PORT
              value: $(SVC_OBPROXY_SERVICE_PORT)
            - name: DATABASE_USERNAME
              value: root@metatenant#metadb
            - name: DATABASE_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: sc-metatenant-root
                  key: password
            - name: DATABASE_NAME
              value: odc
            - name: ODC_SERVER_PORT
              value: '8989'
          resources:
            limits:
              memory: 8Gi
