// Code generated by go generate; DO NOT EDIT.
package obcluster

func init() {
	taskMap[tWaitOBZoneTopologyMatch] = WaitOBZoneTopologyMatch
	taskMap[tWaitOBZoneDeleted] = WaitOBZoneDeleted
	taskMap[tModifyOBZoneReplica] = ModifyOBZoneReplica
	taskMap[tDeleteOBZone] = DeleteOBZone
	taskMap[tCreateOBZone] = CreateOBZone
	taskMap[tBootstrap] = Bootstrap
	taskMap[tCreateUsers] = CreateUsers
	taskMap[tMaintainOBParameter] = MaintainOBParameter
	taskMap[tValidateUpgradeInfo] = ValidateUpgradeInfo
	taskMap[tUpgradeCheck] = UpgradeCheck
	taskMap[tBackupEssentialParameters] = BackupEssentialParameters
	taskMap[tBeginUpgrade] = BeginUpgrade
	taskMap[tRollingUpgradeByZone] = RollingUpgradeByZone
	taskMap[tFinishUpgrade] = FinishUpgrade
	taskMap[tModifySysTenantReplica] = ModifySysTenantReplica
	taskMap[tCreateServiceForMonitor] = CreateServiceForMonitor
	taskMap[tRestoreEssentialParameters] = RestoreEssentialParameters
	taskMap[tCheckAndCreateUserSecrets] = CheckAndCreateUserSecrets
	taskMap[tCreateOBClusterService] = CreateOBClusterService
	taskMap[tCheckImageReady] = CheckImageReady
	taskMap[tCheckClusterMode] = CheckClusterMode
	taskMap[tCheckMigration] = CheckMigration
	taskMap[tScaleUpOBZones] = ScaleUpOBZones
	taskMap[tExpandPVC] = ExpandPVC
	taskMap[tMountBackupVolume] = MountBackupVolume
	taskMap[tWaitOBZoneBootstrapReady] = WaitOBZoneBootstrapReady
	taskMap[tWaitOBZoneRunning] = WaitOBZoneRunning
}
