// Code generated by go generate; DO NOT EDIT.
package oblogservicezone

func init() {
	taskMap.Register(tCreateNodes, CreateNodes)
	taskMap.Register(tWaitNodesReady, WaitNodesReady)
	taskMap.Register(tWaitNodesRunning, WaitNodesRunning)
	taskMap.Register(tDeleteExcessNodes, DeleteExcessNodes)
	taskMap.Register(tDeleteAllNodes, DeleteAllNodes)
}
