// Code generated by go generate; DO NOT EDIT.
package obtenantrestore

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tStartRestoreJobInOB ttypes.TaskName = "start restore job in ob"
	tStartLogReplay ttypes.TaskName = "start log replay"
	tActivateStandby ttypes.TaskName = "activate standby"
)
