// Code generated by go generate; DO NOT EDIT.
package obtenantrestore

func init() {
	taskMap.Register(tStartRestoreJobInOB, StartRestoreJobInOB)
	taskMap.Register(tStartLogReplay, StartLogReplay)
	taskMap.Register(tActivateStandby, ActivateStandby)
}
