apiVersion: v1
kind: Service
metadata:
  name: svc-oceanbase-todo
spec:
  type: NodePort
  selector:
    app: oceanbase-todo
  ports:
    - name: "http"
      port: 20031
      targetPort: 20031
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceanbase-todo
spec:
  selector:
    matchLabels:
      app: oceanbase-todo
  replicas: 2
  template:
    metadata:
      labels:
        app: oceanbase-todo
    spec:
      containers:
        - name: oceanbase-todo
          image: oceanbase/oceanbase-todo
          imagePullPolicy: IfNotPresent
          ports:
            - name: "http"
              containerPort: 20031
          env:
            - name: DB_HOST
              value: "xxx"
            - name: DB_PORT
              value: "xxx"
            - name: DB_USER
              value: "xxx"
            - name: DB_PASSWORD
              value: "xxx"
            - name: DB_DATABASE
              value: "xxx"
            - name: LISTEN_PORT
              value: "20031"
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 100m
