/*
Copyright (c) 2023 OceanBase
ob-operator is licensed under Mulan PSL v2.
You can use this software according to the terms and conditions of the Mulan PSL v2.
You may obtain a copy of Mulan PSL v2 at:
         http://license.coscl.org.cn/MulanPSL2
THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
See the Mulan PSL v2 for more details.
*/

package types

import "github.com/oceanbase/ob-operator/pkg/task/strategy"

type OperationContext struct {
	Name         string               `json:"name"`
	Tasks        []string             `json:"tasks"`
	Task         string               `json:"task"`
	Idx          int                  `json:"idx"`
	TaskStatus   string               `json:"taskStatus"`
	TaskId       string               `json:"taskId"`
	TargetStatus string               `json:"targetStatus"`
	OnFailure    strategy.FailureRule `json:"failureRule,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationContext) DeepCopyInto(out *OperationContext) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.OnFailure = in.OnFailure
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationContext.
func (in *OperationContext) DeepCopy() *OperationContext {
	if in == nil {
		return nil
	}
	out := new(OperationContext)
	in.DeepCopyInto(out)
	return out
}
