{{- if $.Values.generateUserSecrets }}
  {{- range $secretName := $.Values.userSecrets }}
    {{- if empty (lookup "v1" "Secret" $.Release.Namespace $secretName) }}
--- # the lookup function will return an empty list when dry-running or local rendering
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }} 
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "oceanbase-cluster.labels" $ | nindent 4 }}
data:
  password: {{ randAlphaNum 16 | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}