// Code generated by go generate; DO NOT EDIT.
package obtenantbackuppolicy

func init() {
	taskMap.Register(tConfigureServerForBackup, ConfigureServerForBackup)
	taskMap.Register(tStartBackup, StartBackup)
	taskMap.Register(tStopBackup, StopBackup)
	taskMap.Register(tCheckAndSpawnJobs, CheckAndSpawnJobs)
	taskMap.Register(tCleanOldBackupJobs, CleanOldBackupJobs)
	taskMap.Register(tPauseBackup, PauseBackup)
	taskMap.Register(tResumeBackup, ResumeBackup)
}
