name: build docsite

on:
  push:
    branches:
      - master
      - test-docsite
    paths:
      - 'docsite/**'
  pull_request:
    branches:
      - master
      - test-docsite
    paths:
      - 'docsite/**'

jobs:
  build:
    name: build docsite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: './docsite/yarn.lock'
      - name: Install dependencies
        run: cd docsite && yarn install --frozen-lockfile
      - name: Build website
        run: cd docsite && yarn build