name: run tests

on:
  pull_request:
    branches:
      - master
      - "*_release"
    paths:
      - '**/*.go'
  push:
    branches:
      - master
      - "*_release"
    paths:
      - '**/*.go'

env:
  GO_VERSION: "1.22"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: go mod vendor
        run: go mod vendor

      - name: install tools
        run: make tools

      - name: test webhooks
        run: make test-webhooks
      