name: release images

on: 
  push:
    tags: 
      - "observer-*"
      - "obproxy-*"
      - "obagent-*"
      - "obconfigserver-*"

env:
  tagName: ${{ github.ref_name }}

jobs:
  release-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Version variables
        id: set_version_vars
        run: echo "version=$(echo $tagName | grep -P \"(\d*\.\d*\.\d*\.\d*-\d{18})\" --only-matching)" >> $GITHUB_OUTPUT

      - name: Build and push observer w/o cache
        uses: docker/build-push-action@v2
        if: ${{ startsWith(github.ref_name, "observer-") }}
        with:
          context: ./distribution/oceanbase
          platforms: linux/amd64,linux/arm64
          file: ./distribution/oceanbase/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/oceanbase-cloud-native:${{ steps.set_version_vars.outputs.version }}
          build-args: |
            VERSION:${{ steps.set_version_vars.outputs.version }}
