name: release images

# on:
#   push:
#     branches:
#       - 'master'
#       - '*release'
#       - 'helm-chart'
on: 
  push:
    tags: 
      - '*.*.*'

env:
  GO_VERSION: "1.20"

jobs:
  release-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: go mod vendor
        run: go mod vendor

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create and push manifests
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ${{ vars.DOCKER_REPOSITORY }}:${{ github.ref_name }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_REPOSITORY }}:buildcache,mode=max