// Code generated by go generate; DO NOT EDIT.
package obtenant

func init() {
	taskMap.Register(tCheckTenantTask, CheckTenantTask)
	taskMap.Register(tCheckPoolAndConfigTask, CheckPoolAndConfigTask)
	taskMap.Register(tCreateTenantTaskWithClear, CreateTenantTaskWithClear)
	taskMap.Register(tCreateResourcePoolAndConfigTask, CreateResourcePoolAndConfigTask)
	taskMap.Register(tAddPoolTask, AddPoolTask)
	taskMap.Register(tDeletePoolTask, DeletePoolTask)
	taskMap.Register(tMaintainUnitConfigTask, MaintainUnitConfigTask)
	taskMap.Register(tDeleteTenantTask, DeleteTenantTask)
	taskMap.Register(tCheckAndApplyCharset, CheckAndApplyCharset)
	taskMap.Register(tCreateEmptyStandbyTenant, CreateEmptyStandbyTenant)
	taskMap.Register(tCheckPrimaryTenantLSIntegrity, CheckPrimaryTenantLSIntegrity)
	taskMap.Register(tCreateTenantRestoreJobCR, CreateTenantRestoreJobCR)
	taskMap.Register(tWatchRestoreJobToFinish, WatchRestoreJobToFinish)
	taskMap.Register(tCancelTenantRestoreJob, CancelTenantRestoreJob)
	taskMap.Register(tUpgradeTenantIfNeeded, UpgradeTenantIfNeeded)
	taskMap.Register(tCheckAndApplyUnitNum, CheckAndApplyUnitNum)
	taskMap.Register(tCheckAndApplyWhiteList, CheckAndApplyWhiteList)
	taskMap.Register(tCheckAndApplyPrimaryZone, CheckAndApplyPrimaryZone)
	taskMap.Register(tCheckAndApplyLocality, CheckAndApplyLocality)
	taskMap.Register(tCreateUserWithCredentialSecrets, CreateUserWithCredentialSecrets)
}
