// Code generated by go generate; DO NOT EDIT.
package obtenant

import ttypes "github.com/oceanbase/ob-operator/pkg/task/types"

const (
	tCheckTenant                     ttypes.TaskName = "check tenant"
	tCheckPoolAndConfig              ttypes.TaskName = "check pool and config"
	tCreateTenantWithClear           ttypes.TaskName = "create tenant with clear"
	tCreateResourcePoolAndConfig     ttypes.TaskName = "create resource pool and config"
	tAddPool                         ttypes.TaskName = "add pool"
	tDeletePool                      ttypes.TaskName = "delete pool"
	tMaintainUnitConfig              ttypes.TaskName = "maintain unit config"
	tDeleteTenant                    ttypes.TaskName = "delete tenant"
	tCheckAndApplyCharset            ttypes.TaskName = "check and apply charset"
	tCreateEmptyStandbyTenant        ttypes.TaskName = "create empty standby tenant"
	tCheckPrimaryTenantLsIntegrity   ttypes.TaskName = "check primary tenant ls integrity"
	tCreateTenantRestoreJobCR        ttypes.TaskName = "create tenant restore job cr"
	tWatchRestoreJobToFinish         ttypes.TaskName = "watch restore job to finish"
	tCancelTenantRestoreJob          ttypes.TaskName = "cancel tenant restore job"
	tUpgradeTenantIfNeeded           ttypes.TaskName = "upgrade tenant if needed"
	tCheckAndApplyUnitNum            ttypes.TaskName = "check and apply unit num"
	tCheckAndApplyWhiteList          ttypes.TaskName = "check and apply white list"
	tCheckAndApplyPrimaryZone        ttypes.TaskName = "check and apply primary zone"
	tCheckAndApplyLocality           ttypes.TaskName = "check and apply locality"
	tCreateUserWithCredentialSecrets ttypes.TaskName = "create user with credential secrets"
)
